# Generated by Django 4.2.5 on 2023-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
